import { addDays, format } from 'date-fns';

interface TaskTemplate {
  pillar: 'physical' | 'nutrition' | 'mental' | 'spiritual';
  title: string;
  description: string;
  duration_minutes: number;
  quran_reference?: string;
  hadith_reference?: string;
  scientific_reference?: string;
}

const physicalTasks: TaskTemplate[] = [
  { pillar: 'physical', title: 'Morning Walk After Fajr', description: 'Take a gentle 10-minute walk after Fajr prayer. Walking in the early morning sunlight helps regulate your circadian rhythm and boosts vitamin D.', duration_minutes: 10, hadith_reference: 'O Allah, bless my Ummah in their early mornings. (Abu Dawud)', scientific_reference: 'Morning sunlight exposure increases serotonin production and improves sleep quality. A 2017 study found just 10 min of morning light exposure improved alertness by 58%.' },
  { pillar: 'physical', title: 'Gentle Stretching Routine', description: 'Perform 5 minutes of gentle stretching focusing on your back, shoulders, and legs. The positions in Salah are themselves a form of beneficial stretching.', duration_minutes: 5, scientific_reference: 'Regular stretching reduces muscle tension, improves flexibility by up to 20% in 4 weeks, and lowers cortisol levels according to the Journal of Physical Therapy Science.' },
  { pillar: 'physical', title: 'Bodyweight Strength Circuit', description: 'Simple circuit: 10 squats, 8 push-ups (modified if needed), 20-second plank. Rest 30 seconds between exercises. Build strength the halal way.', duration_minutes: 15, hadith_reference: 'The strong believer is better and more beloved to Allah than the weak believer. (Sahih Muslim)', scientific_reference: 'Bodyweight exercises improve muscle strength, bone density, and metabolic health. Even 15 min of resistance training 3x/week reduces all-cause mortality by 21%.' },
  { pillar: 'physical', title: 'Walk to the Mosque', description: 'Walk to the nearest mosque for one of your prayers today. Every step is recorded as a good deed and is excellent cardio exercise.', duration_minutes: 20, hadith_reference: 'Every step taken towards the mosque is a charity (sadaqah). (Sahih Bukhari)', scientific_reference: 'Harvard research shows walking 30 min/day reduces heart disease risk by 30-40% and improves mood through endorphin release.' },
  { pillar: 'physical', title: 'Wudu Micro-Stretches', description: 'Before or after wudu, add gentle neck rolls (5 each direction), shoulder shrugs (10 reps), and wrist rotations (10 each). These joints are activated during wudu.', duration_minutes: 5, scientific_reference: 'Micro-mobility exercises throughout the day reduce joint stiffness by 35% and prevent repetitive strain injuries.' },
  { pillar: 'physical', title: 'Evening Walk Before Maghrib', description: 'Take a calming 15-minute walk before Maghrib prayer. Use this time for quiet reflection, observing nature, and breathing fresh air.', duration_minutes: 15, scientific_reference: 'Evening walks aid digestion, lower post-meal blood sugar by up to 30%, and promote relaxation by activating the parasympathetic nervous system.' },
  { pillar: 'physical', title: 'Deep Breathing After Salah', description: 'After Dhuhr prayer, practice 4-7-8 breathing: inhale for 4 counts, hold for 7, exhale slowly for 8. Do 4 rounds.', duration_minutes: 5, quran_reference: 'Verily, in the remembrance of Allah do hearts find rest. (13:28)', scientific_reference: 'The 4-7-8 breathing technique activates the vagus nerve, reducing anxiety by up to 37% and lowering resting heart rate.' },
  { pillar: 'physical', title: 'Stair Climbing Challenge', description: 'Take the stairs instead of the elevator every chance today. If at home, climb stairs 5 times up and down as a mini workout.', duration_minutes: 10, hadith_reference: 'The strong believer is better and more beloved to Allah than the weak believer, though both are good. (Sahih Muslim)', scientific_reference: 'Climbing 3-5 flights of stairs daily reduces cardiovascular disease risk by 20%. It burns 2-3x more calories than walking on flat ground.' },
  { pillar: 'physical', title: 'Standing Desk or Movement Breaks', description: 'Set a reminder to stand up and move for 2 minutes every 30 minutes of sitting. Do light stretches, walk around, or do standing calf raises.', duration_minutes: 10, scientific_reference: 'Breaking up sitting time every 30 min reduces blood sugar spikes by 24% and decreases inflammatory markers by 30% (American Diabetes Association).' },
  { pillar: 'physical', title: 'Core Strengthening Session', description: 'Simple core routine: 3 sets of 20-second planks, 10 bicycle crunches, and 10 bird-dogs. Core strength supports your back during long periods of standing in Salah.', duration_minutes: 10, scientific_reference: 'Core strengthening exercises reduce lower back pain by 43% and improve posture and balance (Journal of Physical Therapy Science, 2019).' },
  { pillar: 'physical', title: 'Cold Water Splash Wakeup', description: 'Splash cold water on your face upon waking, as part of wudu. This Sunnah practice triggers the dive reflex, instantly boosting alertness.', duration_minutes: 3, hadith_reference: 'When any one of you wakes from sleep, let him wash his hands before dipping them in the vessel. (Sahih Muslim)', scientific_reference: 'Cold water exposure activates the sympathetic nervous system, increasing norepinephrine by 200-300%, improving alertness and mood.' },
  { pillar: 'physical', title: 'Progressive Walking', description: 'Walk 15 minutes today. Alternate between normal pace for 3 min and brisk pace for 2 min. This interval approach builds cardiovascular fitness gradually.', duration_minutes: 15, scientific_reference: 'Interval walking training improves cardiovascular fitness 20% more than continuous walking at the same duration (British Journal of Sports Medicine).' },
  { pillar: 'physical', title: 'Balance Practice', description: 'Stand on one leg for 30 seconds, then switch. Do 3 rounds each side. Balance training strengthens ankles and improves stability for prayer positions.', duration_minutes: 5, scientific_reference: 'Balance training reduces fall risk by 40% and improves proprioception. Poor balance at any age correlates with higher mortality risk (British Journal of Sports Medicine, 2022).' },
  { pillar: 'physical', title: 'Swimming or Water Exercise', description: 'If possible, swim or do water exercises today. Swimming is a Sunnah sport and provides full-body exercise with minimal joint impact.', duration_minutes: 30, hadith_reference: 'Teach your children swimming, archery, and horseback riding. (Umar ibn al-Khattab)', scientific_reference: 'Swimming improves cardiovascular fitness by 10% and reduces joint pain by 40% compared to land-based exercise, making it ideal for all fitness levels.' },
  { pillar: 'physical', title: 'Flexibility Flow', description: 'Gentle 10-minute flexibility routine: touch your toes (hold 20s), child\'s pose (hold 30s), seated twist (hold 20s each side), hip flexor stretch (hold 20s each side).', duration_minutes: 10, scientific_reference: 'Flexibility training improves range of motion by 15-25% in 4 weeks and reduces exercise-related injury risk by 30% (ACSM Guidelines).' },
];

const nutritionTasks: TaskTemplate[] = [
  { pillar: 'nutrition', title: 'Sunnah: Drink Water in 3 Sips', description: 'Drink a glass of water upon waking. Sit down, say Bismillah, and drink in three measured sips. This Sunnah helps your body absorb water more effectively.', duration_minutes: 2, hadith_reference: 'Do not drink in one gulp like a camel, but drink in two or three sips. Say Bismillah when you drink and Alhamdulillah when you finish. (Tirmidhi)', scientific_reference: 'Drinking water slowly in sips allows better cellular absorption and reduces kidney strain. Hydration on waking boosts metabolism by 24% for 90 minutes.' },
  { pillar: 'nutrition', title: 'Eat 3 Dates', description: 'Have 3 dates as a snack or to break your fast. Dates are a Sunnah superfood packed with fiber, potassium, magnesium, and natural sugars for sustained energy.', duration_minutes: 5, hadith_reference: 'When one of you breaks his fast, let him break it with dates, for they are a blessing. (Abu Dawud)', scientific_reference: 'Dates contain 23 amino acids, are rich in antioxidants, and provide 6.7g of fiber per 100g. They stabilize blood sugar better than processed sugars.' },
  { pillar: 'nutrition', title: 'The 1/3 Rule at Lunch', description: 'At lunch today, practice the Prophetic 1/3 rule: fill your stomach 1/3 food, 1/3 water, 1/3 air. Eat slowly, chew well, and stop before feeling full.', duration_minutes: 15, hadith_reference: 'The son of Adam fills no vessel worse than his stomach. A few mouthfuls are enough. If he must eat more, then 1/3 food, 1/3 drink, 1/3 air. (Tirmidhi)', scientific_reference: 'Eating to 70-80% fullness reduces metabolic syndrome risk by 30% and extends lifespan, as shown in Okinawan centenarian studies.' },
  { pillar: 'nutrition', title: 'Add Olive Oil to Your Meal', description: 'Drizzle extra virgin olive oil on your salad, bread, or dish. The Quran calls the olive tree "blessed" and modern science confirms its extraordinary benefits.', duration_minutes: 2, quran_reference: 'A blessed tree, an olive, neither of the east nor of the west, whose oil would almost glow even if untouched by fire. (24:35)', scientific_reference: 'Extra virgin olive oil reduces inflammation, LDL cholesterol by 10-15%, and cardiovascular disease risk by 30% (PREDIMED trial, NEJM 2018).' },
  { pillar: 'nutrition', title: 'Honey and Warm Water Morning', description: 'Mix a teaspoon of raw honey into warm (not hot) water and drink it in the morning. This Quranic remedy has remarkable antibacterial and prebiotic properties.', duration_minutes: 3, quran_reference: 'There comes from their bellies a drink of varying colors, in which there is healing for people. Surely in that is a sign for those who reflect. (16:69)', scientific_reference: 'Manuka honey has clinically proven antibacterial, anti-inflammatory, and wound-healing properties. Raw honey also acts as a prebiotic, feeding beneficial gut bacteria.' },
  { pillar: 'nutrition', title: 'Mindful Eating Practice', description: 'At dinner, say Bismillah, eat with your right hand, and chew each bite 20-30 times. Focus on the texture, flavor, and aroma. Eat without screens.', duration_minutes: 20, hadith_reference: 'Say Bismillah, eat with your right hand, and eat from what is nearest to you. (Sahih Bukhari)', scientific_reference: 'Mindful eating reduces overeating by 25%, improves nutrient absorption by 20%, and significantly reduces binge-eating behaviors (Harvard Health, 2020).' },
  { pillar: 'nutrition', title: 'Black Seed (Habbatus Sauda)', description: 'Take a teaspoon of black seed oil or sprinkle black seeds on your food. The Prophet called it a cure for everything except death.', duration_minutes: 2, hadith_reference: 'Use this black seed, for it contains a cure for every disease except death. (Sahih Bukhari)', scientific_reference: 'Thymoquinone in black seeds shows anti-inflammatory, antioxidant, and immune-boosting properties. Clinical trials show it reduces blood sugar and cholesterol.' },
  { pillar: 'nutrition', title: 'Increase Vegetable Intake', description: 'Add an extra serving of vegetables to one meal today. Choose colorful vegetables for maximum antioxidant benefit. The Quran mentions many beneficial plants.', duration_minutes: 5, quran_reference: 'He it is who sends down water from the sky, from which you drink and from which grow trees on which you pasture your cattle. He causes to grow for you crops, olives, date palms, grapes, and every kind of fruit. (16:10-11)', scientific_reference: 'Each additional daily serving of vegetables reduces cardiovascular disease risk by 10% and colorectal cancer risk by 9% (Lancet, 2017).' },
  { pillar: 'nutrition', title: 'Sunnah Fasting (Optional)', description: 'If you feel ready, fast today (Monday or Thursday). Even a partial fast until noon offers significant health benefits. Break your fast with dates and water.', duration_minutes: 5, hadith_reference: 'The Prophet (PBUH) used to fast on Mondays and Thursdays. (Sunan an-Nasa\'i)', scientific_reference: 'Nobel Prize-winning research on autophagy shows intermittent fasting triggers cellular repair, removing damaged proteins and regenerating new cells.' },
  { pillar: 'nutrition', title: 'Hydration Check', description: 'Track your water intake today. Aim for 8 glasses (2 liters). Set reminders to drink water between prayers: after Fajr, Dhuhr, Asr, Maghrib, and Isha.', duration_minutes: 3, scientific_reference: 'Even 2% dehydration impairs cognitive performance by 20% and physical performance by 25%. Adequate hydration improves kidney function and reduces headache frequency by 50%.' },
  { pillar: 'nutrition', title: 'Cook a Sunnah Meal', description: 'Prepare a meal using Sunnah ingredients: barley (talbina), lamb, dates, olive oil, or lentils. Cooking your own food is healthier and more rewarding.', duration_minutes: 30, hadith_reference: 'The Talbina (barley porridge) soothes the heart of the patient and relieves some of his grief. (Sahih Bukhari)', scientific_reference: 'Home cooking is associated with 28% lower body weight and better nutrient intake compared to frequent restaurant dining (Johns Hopkins, 2014).' },
  { pillar: 'nutrition', title: 'No Sugar Challenge', description: 'Avoid all added sugar today. Use natural sweeteners like dates, honey, or fruit instead. Read labels — sugar hides in many packaged foods.', duration_minutes: 3, scientific_reference: 'Reducing added sugar intake to below 25g/day decreases heart disease risk by 36%, reduces inflammation markers, and improves dental health (AHA Guidelines).' },
  { pillar: 'nutrition', title: 'Apple Cider Vinegar Tonic', description: 'Mix 1 tablespoon of apple cider vinegar in water before a meal. This helps with digestion and blood sugar regulation.', duration_minutes: 2, scientific_reference: 'A tablespoon of ACV before meals reduces post-meal blood sugar spikes by 20-34% and increases satiety, leading to eating 200-275 fewer calories per day (European Journal of Clinical Nutrition).' },
  { pillar: 'nutrition', title: 'Eat with Your Family', description: 'Share at least one meal with family or friends today. Eating together is Sunnah and brings barakah (blessings) to the food.', duration_minutes: 30, hadith_reference: 'Eat together and do not eat separately, for the blessing is in the gathering. (Ibn Majah)', scientific_reference: 'Family meals are associated with 24% higher consumption of healthy foods, 20% lower risk of eating disorders, and better mental health in all age groups (Pediatrics, 2011).' },
  { pillar: 'nutrition', title: 'Reduce Processed Food', description: 'Replace one processed food item today with a whole food alternative. Choose fresh fruit over packaged snacks, whole grains over refined bread.', duration_minutes: 5, scientific_reference: 'Ultra-processed foods increase all-cause mortality risk by 26%. Replacing just 10% of processed foods with whole foods reduces cancer risk by 12% (BMJ, 2019).' },
];

const mentalTasks: TaskTemplate[] = [
  { pillar: 'mental', title: 'Gratitude Journaling (Shukr)', description: 'Write down 3 things you are grateful to Allah for today. Be specific: not just "family" but "my mother called to check on me." This rewires your brain for positivity.', duration_minutes: 5, quran_reference: 'If you are grateful, I will surely increase you in favor. (14:7)', scientific_reference: 'Gratitude journaling increases happiness by 25%, improves sleep quality by 10%, and reduces depression symptoms by 35% (Journal of Personality & Social Psychology).' },
  { pillar: 'mental', title: 'Digital Detox Hour', description: 'Put your phone on silent and away for 1 hour. Use this time for reading Quran, spending time with family, or quiet contemplation of Allah\'s creation.', duration_minutes: 60, scientific_reference: 'Reducing screen time by 1 hour/day reduces depression by 35% and anxiety by 20% (Journal of Social and Clinical Psychology, 2022).' },
  { pillar: 'mental', title: 'Forgiveness Reflection', description: 'Think of someone who has wronged you and consciously forgive them in your heart. Make dua for them. Forgiveness frees your heart from the weight of resentment.', duration_minutes: 10, quran_reference: 'Let them pardon and forgive. Do you not love that Allah should forgive you? And Allah is Forgiving and Merciful. (24:22)', scientific_reference: 'Forgiveness therapy lowers blood pressure by 5-10 mmHg, reduces chronic pain by 20%, and improves cardiovascular health (American Psychological Association).' },
  { pillar: 'mental', title: 'Nature Contemplation (Tafakkur)', description: 'Spend 10 minutes outdoors observing Allah\'s creation: the sky, trees, birds, water. Reflect on the signs in nature and how they point to the Creator.', duration_minutes: 10, quran_reference: 'Indeed, in the creation of the heavens and the earth and the alternation of the night and day are signs for those of understanding. (3:190)', scientific_reference: 'Spending 20+ minutes in nature reduces cortisol by 21%, blood pressure by 5%, and heart rate by 6%. Nature exposure also improves attention span by 20% (Frontiers in Psychology).' },
  { pillar: 'mental', title: 'Positive Self-Talk with Tawakkul', description: 'Notice one negative thought today and replace it with trust in Allah\'s plan. Write it down: "Allah is the best of planners. I trust His wisdom for me."', duration_minutes: 5, quran_reference: 'And whoever puts their trust in Allah, He will be enough for them. Indeed, Allah will accomplish His purpose. (65:3)', scientific_reference: 'Cognitive reframing reduces anxiety symptoms by 20-30% and improves resilience. Replacing negative self-talk with positive affirmations literally rewires neural pathways (CBT research).' },
  { pillar: 'mental', title: 'Acts of Kindness', description: 'Perform one deliberate act of kindness today: help a neighbor, call a relative, compliment a stranger, or donate something small. Feel the joy of giving.', duration_minutes: 15, hadith_reference: 'The most beloved people to Allah are those who are most beneficial to people. (Tabarani)', scientific_reference: 'Acts of kindness trigger oxytocin release ("love hormone"), reducing blood pressure by 5% and significantly improving heart health and mood (Journal of Social Psychology).' },
  { pillar: 'mental', title: 'Worry Journaling', description: 'Write down your current worries, then next to each one write: "Is this in my control?" For things outside your control, practice tawakkul and let them go.', duration_minutes: 10, quran_reference: 'Say: Nothing will happen to us except what Allah has decreed for us. He is our Protector. And in Allah let the believers put their trust. (9:51)', scientific_reference: 'Expressive writing about worries reduces anxiety by 25% and intrusive thoughts by 40%. Categorizing worries as controllable/uncontrollable reduces rumination (Journal of Experimental Psychology).' },
  { pillar: 'mental', title: 'Read for 15 Minutes', description: 'Read a book (not on a screen) for 15 minutes. Choose Islamic literature, self-development, or any beneficial knowledge. Reading is a gift from Allah.', duration_minutes: 15, quran_reference: 'Read! In the name of your Lord who created. (96:1)', scientific_reference: 'Reading for 30 min/day reduces stress by 68%, improves memory, and may delay cognitive decline by 2-5 years (Neurology journal, 2013).' },
  { pillar: 'mental', title: 'Intention Setting (Niyyah)', description: 'Before starting your day, set 3 clear intentions. Write them down with the Islamic opening: "I intend to... for the sake of Allah." Aligning intentions purifies actions.', duration_minutes: 5, hadith_reference: 'Actions are judged by intentions, and every person will be rewarded according to what they intended. (Sahih Bukhari)', scientific_reference: 'Goal-setting with written intentions increases achievement by 42% compared to unwritten goals (Dominican University study). Morning intention-setting improves focus throughout the day.' },
  { pillar: 'mental', title: 'Patience Practice (Sabr)', description: 'Choose one frustrating situation today and respond with deliberate patience. Take 3 deep breaths before reacting. Say "HasbunAllahu wa ni\'mal wakeel."', duration_minutes: 5, quran_reference: 'O you who believe! Seek help through patience and prayer. Indeed, Allah is with those who are patient. (2:153)', scientific_reference: 'Practicing delayed reactivity (pausing before responding) reduces conflict by 40% and improves emotional intelligence scores by 25% (Emotional Intelligence journal).' },
  { pillar: 'mental', title: 'Compassion Meditation', description: 'Sit quietly for 5 minutes. Think of someone suffering and send them prayers. Then extend that compassion to yourself, your family, your community, and all of humanity.', duration_minutes: 5, hadith_reference: 'Those who show mercy are shown mercy by the Most Merciful. Show mercy to those on earth, and the One above the heavens will show mercy to you. (Tirmidhi)', scientific_reference: 'Loving-kindness meditation increases positive emotions by 30%, reduces inflammation markers, and improves social connection (Journal of Positive Psychology).' },
  { pillar: 'mental', title: 'Declutter One Space', description: 'Spend 10 minutes organizing one small area: a desk drawer, a shelf, or your bag. Physical order creates mental clarity and reduces cognitive load.', duration_minutes: 10, hadith_reference: 'Cleanliness is half of faith. (Sahih Muslim)', scientific_reference: 'Cluttered environments increase cortisol by 20% and reduce ability to focus. Decluttering a space improves mood and reduces anxiety (Personality and Social Psychology Bulletin).' },
  { pillar: 'mental', title: 'Social Connection', description: 'Reach out to someone you have not spoken to in a while. Send a message, make a call, or visit a neighbor. Maintaining ties is a Sunnah and crucial for mental health.', duration_minutes: 15, hadith_reference: 'Whoever wishes that his provision be increased and his lifespan extended, let him maintain ties of kinship. (Sahih Bukhari)', scientific_reference: 'Strong social connections reduce mortality risk by 50%, reduce depression by 40%, and improve immune function (PLOS Medicine meta-analysis).' },
  { pillar: 'mental', title: 'Mindful Breathing', description: 'Set a timer for 5 minutes. Close your eyes and focus only on your breathing. When your mind wanders, gently return to the breath. This is a form of muraqaba (self-awareness).', duration_minutes: 5, scientific_reference: 'Mindfulness meditation reduces anxiety by 30-40%, improves attention span, and physically increases grey matter density in the brain after just 8 weeks (Harvard/Mass General, Psychiatry Research).' },
  { pillar: 'mental', title: 'Evening Review', description: 'Before sleep, review your day: What went well? What could be better? Make istighfar for mistakes and set intention for tomorrow. This Sunnah practice builds self-awareness.', duration_minutes: 10, hadith_reference: 'Call yourselves to account before you are called to account. (Umar ibn al-Khattab)', scientific_reference: 'Daily self-reflection improves job performance by 23% and accelerates personal growth by helping identify patterns and areas for improvement (Harvard Business School study).' },
];

const spiritualTasks: TaskTemplate[] = [
  { pillar: 'spiritual', title: 'Morning Adhkar', description: 'After Fajr, recite the morning remembrance: SubhanAllah 33x, Alhamdulillah 33x, Allahu Akbar 33x, then complete to 100 with La ilaha illallah. Use your fingers to count.', duration_minutes: 10, hadith_reference: 'Whoever says SubhanAllah 33 times, Alhamdulillah 33 times, and Allahu Akbar 33 times after each prayer, and completes 100 with La ilaha illallah... his sins will be forgiven. (Sahih Muslim)', scientific_reference: 'Repetitive devotional practices activate the parasympathetic nervous system, reducing cortisol by 20-25% and lowering blood pressure. This mirrors the "relaxation response" described by Dr. Herbert Benson.' },
  { pillar: 'spiritual', title: 'Read 1 Page of Quran', description: 'Read just one page of the Quran with meaning today. Quality over quantity. Try to understand what Allah is telling you. Reflect on how it applies to your life.', duration_minutes: 10, quran_reference: 'This is a blessed Book which We have revealed to you, that they might reflect upon its verses and that those of understanding would be reminded. (38:29)', scientific_reference: 'Focused reading for meaning activates the brain\'s default mode network, improving comprehension, memory, and empathy. Reading sacred texts specifically reduces existential anxiety.' },
  { pillar: 'spiritual', title: 'Pray 2 Rakat Sunnah', description: 'Add 2 voluntary rakat before or after one of your fard prayers today. Start small and build. These extra prayers build closeness to Allah.', duration_minutes: 5, hadith_reference: 'Whoever prays twelve rakat of Sunnah, Allah will build for him a house in Paradise. (Sahih Muslim)', scientific_reference: 'The physical movements of Salah (standing, bowing, prostrating) improve flexibility, balance, and joint mobility. Sujud increases blood flow to the brain by 15%.' },
  { pillar: 'spiritual', title: 'Istighfar 100 Times', description: 'Say "Astaghfirullah" 100 times throughout the day, not in one sitting but distributed across your activities. This purifies the heart and brings peace.', duration_minutes: 10, hadith_reference: 'By Allah, I seek forgiveness from Allah and I repent to Him more than seventy times a day. (Sahih Bukhari)', scientific_reference: 'Repetitive calming phrases reduce rumination and promote a meditative state. Regular practice of mantras reduces amygdala reactivity (stress center) by 15-20% (Neuroscience & Biobehavioral Reviews).' },
  { pillar: 'spiritual', title: 'Dua Before Sleep', description: 'Before sleeping, perform wudu, recite Ayatul Kursi, blow on your palms while reciting Al-Ikhlas, Al-Falaq, and An-Nas, then wipe over your body.', duration_minutes: 5, hadith_reference: 'The Prophet (PBUH) would recite the last 3 surahs, blow into his hands, and wipe them over his body before sleeping. (Sahih Bukhari)', scientific_reference: 'Pre-sleep relaxation rituals improve sleep onset latency by 30% and increase deep sleep duration by 15-20%. Consistent bedtime routines are the strongest predictor of sleep quality (Sleep Medicine Reviews).' },
  { pillar: 'spiritual', title: 'Dhikr Walking Meditation', description: 'During a walk, silently recite "La ilaha illallah" with each step. Synchronize the remembrance with your breathing. Left foot: "La ilaha", right foot: "illallah."', duration_minutes: 15, quran_reference: 'Those who remember Allah while standing, sitting, and lying on their sides, and reflect on the creation of the heavens and earth. (3:191)', scientific_reference: 'Walking meditation combining mantras with movement reduces stress hormones by 25% more effectively than walking or meditation alone. It also improves cardiovascular fitness simultaneously.' },
  { pillar: 'spiritual', title: 'Learn a New Dua', description: 'Memorize one new dua today. Write it on a sticky note and review it throughout the day. Suggestions: Dua for entering the home, dua for travel, or dua for protection.', duration_minutes: 10, hadith_reference: 'Dua is the essence of worship. (Tirmidhi)', scientific_reference: 'Memorization exercises strengthen the hippocampus and improve working memory capacity. Learning in small daily chunks (spaced repetition) is 2-3x more effective than cramming.' },
  { pillar: 'spiritual', title: 'Give Sadaqah', description: 'Give charity today, no matter how small. It could be money, food, a smile, or removing something harmful from the road. Every act of goodness is sadaqah.', duration_minutes: 5, hadith_reference: 'Even a smile in the face of your brother is charity. Removing something harmful from the road is charity. (Tirmidhi)', scientific_reference: 'Giving to others activates the brain\'s reward centers, releasing dopamine and oxytocin. Regular charitable giving is associated with 24% greater happiness and 68% lower stress (NIH study).' },
  { pillar: 'spiritual', title: 'Recite Surah Al-Mulk', description: 'Recite Surah Al-Mulk (Chapter 67) before sleeping. It is 30 verses and takes about 5-7 minutes. It intercedes for its reciter in the grave.', duration_minutes: 7, hadith_reference: 'There is a surah in the Quran with thirty verses that interceded for a man until he was forgiven. It is Surah Al-Mulk. (Tirmidhi)', scientific_reference: 'Reciting familiar religious texts before sleep reduces pre-sleep anxiety, decreases sleep latency, and improves subjective sleep quality (Journal of Religion and Health).' },
  { pillar: 'spiritual', title: 'Tahajjud (Night Prayer)', description: 'Wake up 15-20 minutes before Fajr and pray 2 rakat of Tahajjud. Make heartfelt dua in the last third of the night when Allah descends to the lowest heaven.', duration_minutes: 15, quran_reference: 'And from part of the night, pray with it as additional worship for you; it is expected that your Lord will resurrect you to a praised station. (17:79)', scientific_reference: 'Early morning waking (3-5 AM) correlates with peak cortisol awakening response, enhancing alertness and cognitive function. Prayer at this time combines the benefits of meditation with optimal brain chemistry.' },
  { pillar: 'spiritual', title: 'Salawat upon the Prophet', description: 'Say "Allahumma salli ala Muhammad wa ala ali Muhammad" at least 100 times today. Spread it throughout your day: while commuting, waiting, or walking.', duration_minutes: 10, hadith_reference: 'Whoever sends blessings upon me once, Allah will send blessings upon him ten times. (Sahih Muslim)', scientific_reference: 'Repetitive positive phrases activate the brain\'s prefrontal cortex (associated with wellbeing) and reduce activity in the amygdala (fear center) by 15% (NeuroImage journal).' },
  { pillar: 'spiritual', title: 'Reflect on Death (Tafakkur al-Mawt)', description: 'Spend 5 minutes thinking about the reality of death and the akhirah. This is not morbid but sobering. It helps prioritize what truly matters.', duration_minutes: 5, hadith_reference: 'Remember often the destroyer of pleasures (death). (Tirmidhi)', scientific_reference: 'Terror Management Theory research shows that brief mortality reflection increases gratitude by 40%, generosity by 30%, and life satisfaction, as it clarifies personal values and priorities.' },
  { pillar: 'spiritual', title: 'Use the Miswak', description: 'Use a miswak (teeth-cleaning twig from Salvadora persica) before prayer. This beloved Sunnah has remarkable antibacterial properties verified by modern dentistry.', duration_minutes: 3, hadith_reference: 'The miswak is a means of purification for the mouth and is pleasing to the Lord. (Sunan an-Nasa\'i)', scientific_reference: 'The WHO recognizes miswak as effective for oral hygiene. It contains natural fluoride, silica, and salvadorine which are antibacterial and anti-plaque (Journal of Periodontology).' },
  { pillar: 'spiritual', title: 'Evening Adhkar', description: 'Before Maghrib, recite the evening remembrance: Ayatul Kursi, the last 2 verses of Al-Baqarah, and the morning/evening supplications from the Sunnah.', duration_minutes: 10, hadith_reference: 'Whoever recites the last two verses of Surah Al-Baqarah at night, they will be sufficient for him. (Sahih Bukhari)', scientific_reference: 'Evening contemplative practices reduce pre-sleep cognitive arousal by 40%, lower cortisol before bed, and significantly improve overall sleep architecture (Sleep Medicine journal).' },
  { pillar: 'spiritual', title: 'Attend a Halaqah or Listen to a Lecture', description: 'Attend an Islamic study circle or listen to a 15-minute lecture from a trusted scholar. Knowledge is the foundation of practice.', duration_minutes: 15, hadith_reference: 'Whoever takes a path upon which to obtain knowledge, Allah makes the path to Paradise easy for him. (Sahih Muslim)', scientific_reference: 'Lifelong learning reduces cognitive decline by 30%, improves neuroplasticity, and is associated with greater life satisfaction and lower rates of depression (Lancet Neurology).' },
];

const taskPool: Record<string, TaskTemplate[]> = {
  physical: physicalTasks,
  nutrition: nutritionTasks,
  mental: mentalTasks,
  spiritual: spiritualTasks,
};

interface GeneratedTask {
  challenge_id: string;
  day_number: number;
  scheduled_date: string;
  pillar: string;
  title: string;
  description: string;
  duration_minutes: number;
  quran_reference: string | null;
  hadith_reference: string | null;
  scientific_reference: string | null;
  difficulty: number;
  points_reward: number;
}

export function generateChallengeTasks(
  challengeId: string,
  challengeType: string,
  startDate: Date,
  _fitnessLevel: string,
  _spiritualLevel: string
): GeneratedTask[] {
  const totalDays = challengeType === '30_days' ? 30 : challengeType === '100_days' ? 100 : 365;
  const pillars: Array<'physical' | 'nutrition' | 'mental' | 'spiritual'> = ['physical', 'nutrition', 'mental', 'spiritual'];
  const tasks: GeneratedTask[] = [];

  for (let day = 1; day <= totalDays; day++) {
    const scheduledDate = format(addDays(startDate, day - 1), 'yyyy-MM-dd');
    const progressRatio = day / totalDays;
    const difficulty = Math.min(10, Math.ceil(progressRatio * 10));
    const basePoints = 10 + Math.floor(progressRatio * 15);

    // 1% better: start with 2 tasks, scale up
    const tasksPerDay = day <= 5 ? 2 : day <= 14 ? 3 : 4;
    const dayPillars = pillars.slice(0, tasksPerDay);

    for (const pillar of dayPillars) {
      const pool = taskPool[pillar];
      const template = pool[(day - 1) % pool.length];

      // Scale duration down in early days for gentler start
      const durationScale = day <= 5 ? 0.5 : day <= 14 ? 0.7 : day <= 21 ? 0.85 : 1;
      const adjustedDuration = Math.max(2, Math.round(template.duration_minutes * durationScale));

      tasks.push({
        challenge_id: challengeId,
        day_number: day,
        scheduled_date: scheduledDate,
        pillar: template.pillar,
        title: template.title,
        description: template.description,
        duration_minutes: adjustedDuration,
        quran_reference: template.quran_reference ?? null,
        hadith_reference: template.hadith_reference ?? null,
        scientific_reference: template.scientific_reference ?? null,
        difficulty,
        points_reward: basePoints,
      });
    }
  }

  return tasks;
}
